version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "6:00"
      timezone: "Pacific/Honolulu"
    open-pull-requests-limit: 20
    target-branch: "main"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "6:00"
      timezone: "Pacific/Honolulu"
    open-pull-requests-limit: 20
    target-branch: "devrc-2-5-0"
