version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      #day: "sunday"
      #time: "20:00"
      #timezone: "Pacific/Honolulu"
    open-pull-requests-limit: 10
    target-branch: "main"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      #day: "sunday"
      #time: "20:00"
      #timezone: "Pacific/Honolulu"
    open-pull-requests-limit: 10
    target-branch: "devrc-2-5-0"
